export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const USER_WISHLIST = "USER_WISHLIST";
export const USER_ADD_TO_CART = "USER_ADD_TO_CART";
export const GET_USER_CART = "GET_USER_CART";
export const DELETE_USER_CART = "DELETE_USER_CART";
export const GET_USER_ORDERS = "GET_USER_ORDERS";
export const UPDATE_PRODUCT_CART = "UPDATE_PRODUCT_CART";
export const UPDATE_USER = "UPDATE_USER";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";

export const CREATE_ORDER = "CREATE_ORDER";
export const ADD_RATING = "ADD_RATING";

export const EMPTY_USER_CART = "EMPTY_USER_CART";

export const RESET_ALL = "RESET_ALL";

export const GET_ALL_BLOGS = "GET_ALL_BLOGS";
export const GET_BLOG = "GET_BLOG";

export const SEND_ENQUIRY = "SEND_ENQUIRY";